#!/usr/bin/env python3
"""Quality gate hook for Claude Code — PostToolUse entry point.

Reads the PostToolUse JSON event from stdin, extracts the file path,
runs code smell checks, and emits a blocking result when violations
are found. Claude must fix the violations before proceeding.

Generated by /quality-init on {generated_date}.
Do NOT edit thresholds here — edit smell_types.py instead.
"""

from __future__ import annotations

import json
import os
import sys

# Allow importing sibling modules from the same directory.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from smell_checks import check_file  # noqa: E402


def format_violations(file_path: str, smells: list[dict]) -> str:
    """Format smell violations into a human-readable report."""
    lines = [f"CODE SMELL VIOLATIONS in {file_path}:"]
    fixes_needed: set[str] = set()

    for s in smells:
        tag = s["kind"].upper().replace("_", " ")
        detail = s.get("detail", "")
        lines.append(f"  [{tag}] {detail}")
        if "fix" in s:
            fixes_needed.add(s["fix"])

    if fixes_needed:
        lines.append("")
        lines.append("Fix these code smells before moving on:")
        for fix in sorted(fixes_needed):
            lines.append(f"  - {fix}")
        lines.append("Then notify the user what you fixed and why.")

    return "\n".join(lines)


def main() -> None:
    try:
        event = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        # Broken input → fail open (Claude proceeds).
        sys.exit(0)

    file_path = event.get("tool_input", {}).get("file_path", "")

    if not file_path or not os.path.isfile(file_path):
        sys.exit(0)

    smells = check_file(file_path)

    if smells:
        reason = format_violations(file_path, smells)
        # decision: "block" tells Claude Code to stop and fix.
        print(json.dumps({{"decision": "block", "reason": reason}}))

    sys.exit(0)


if __name__ == "__main__":
    main()
