"""Quality gate thresholds and shared types.

Generated by /quality-init on {generated_date}.
Calibrated from project metrics — edit these values to tune sensitivity.

Each threshold shows its source:
  - "p90 = N" means the 90th percentile of existing code was N.
  - "floor = N" means the minimum acceptable threshold.
  - The higher of (p90, floor) is used as the threshold.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

# ── Thresholds ────────────────────────────────────────────────────────
# {threshold_comments}

MAX_COMPLEXITY: int = {max_complexity}
MAX_FUNCTION_LINES: int = {max_function_lines}
MAX_NESTING_DEPTH: int = {max_nesting_depth}
MAX_PARAMETERS: int = {max_parameters}
MAX_FILE_LINES: int = {max_file_lines}
DUPLICATE_MIN_LINES: int = {duplicate_min_lines}
DUPLICATE_MIN_OCCURRENCES: int = {duplicate_min_occurrences}

# ── Fix instructions ──────────────────────────────────────────────────

FIXES: dict[str, str] = {{
    "complexity": "Use extract-method, early returns, guard clauses, or lookup tables.",
    "long_function": "Extract helper functions for distinct logical steps.",
    "deep_nesting": "Use guard clauses and early returns to flatten control flow.",
    "too_many_params": "Group related parameters into a dataclass or options object.",
    "duplicate_block": "Extract repeated code into a shared helper function.",
    "long_file": "Split into smaller modules with clear single responsibilities.",
}}

# ── Skip directories ─────────────────────────────────────────────────

SKIP_DIRS: frozenset[str] = frozenset((
{skip_dirs_entries}
))

# ── Supported extensions ──────────────────────────────────────────────

PYTHON_EXTENSIONS: frozenset[str] = frozenset((".py",))

LIZARD_EXTENSIONS: frozenset[str] = frozenset((
    ".js", ".jsx", ".ts", ".tsx", ".java",
    ".go", ".rs", ".c", ".cpp", ".cc", ".cs",
))

# ── Data classes ──────────────────────────────────────────────────────


@dataclass
class Smell:
    """A single code smell finding."""

    kind: str
    detail: str
    fix: str
    line: Optional[int] = None
    function_name: Optional[str] = None
