"""Orchestrator — routes files to the right analyzer and runs file-level checks.

Generated by /quality-init on {generated_date}.
"""

from __future__ import annotations

import os
import subprocess
from collections import Counter
from pathlib import Path

from smell_types import (
    DUPLICATE_MIN_LINES,
    DUPLICATE_MIN_OCCURRENCES,
    FIXES,
    LIZARD_EXTENSIONS,
    MAX_COMPLEXITY,
    MAX_FILE_LINES,
    MAX_FUNCTION_LINES,
    MAX_PARAMETERS,
    PYTHON_EXTENSIONS,
    SKIP_DIRS,
    Smell,
)


# ── Skip logic ────────────────────────────────────────────────────────


def _should_skip(file_path: str) -> bool:
    """Return True if the file is in a skip directory or unsupported."""
    parts = Path(file_path).parts
    for part in parts:
        if part in SKIP_DIRS:
            return True

    ext = Path(file_path).suffix.lower()
    supported = PYTHON_EXTENSIONS | LIZARD_EXTENSIONS
    return ext not in supported


# ── File-level checks ─────────────────────────────────────────────────


def _check_file_length(source: str, file_path: str) -> list[Smell]:
    """Check if the file exceeds the maximum line count."""
    lines = source.splitlines()
    if len(lines) > MAX_FILE_LINES:
        return [Smell(
            kind="long_file",
            detail=f"{{file_path}}: {{len(lines)}} lines (max {{MAX_FILE_LINES}})",
            fix=FIXES["long_file"],
        )]
    return []


def _check_duplicates(source: str, file_path: str) -> list[Smell]:
    """Detect duplicate code blocks using sliding window comparison."""
    lines = source.splitlines()

    # Filter out trivial lines
    trivial = frozenset(("", "{{", "}}", "else:", "else {{", "pass", "return", "break", "continue"))
    meaningful: list[tuple[int, str]] = []
    for i, line in enumerate(lines, 1):
        stripped = line.strip()
        if stripped and stripped not in trivial and not stripped.startswith(("import ", "from ", "#", "//")):
            meaningful.append((i, stripped))

    if len(meaningful) < DUPLICATE_MIN_LINES:
        return []

    # Build sliding windows
    windows: Counter[tuple[str, ...]] = Counter()
    window_lines: dict[tuple[str, ...], int] = {{}}

    for i in range(len(meaningful) - DUPLICATE_MIN_LINES + 1):
        window = tuple(m[1] for m in meaningful[i : i + DUPLICATE_MIN_LINES])
        if window not in window_lines:
            window_lines[window] = meaningful[i][0]
        windows[window] += 1

    smells: list[Smell] = []
    seen: set[tuple[str, ...]] = set()
    for window, count in windows.items():
        if count >= DUPLICATE_MIN_OCCURRENCES and window not in seen:
            seen.add(window)
            first_line = window_lines[window]
            preview = window[0][:60]
            smells.append(Smell(
                kind="duplicate_block",
                detail=(
                    f"{{file_path}} line {{first_line}}: "
                    f"{{DUPLICATE_MIN_LINES}}-line block repeated {{count}} times "
                    f"(starting with '{{preview}}...')"
                ),
                fix=FIXES["duplicate_block"],
                line=first_line,
            ))

    return smells


# ── Lizard integration (multi-language) ───────────────────────────────


def _check_with_lizard(file_path: str) -> list[Smell]:
    """Run lizard on a non-Python file for complexity, length, and params."""
    try:
        result = subprocess.run(
            ["lizard", file_path, "--csv"],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []  # Lizard not installed or timed out → skip silently

    if result.returncode != 0:
        return []

    smells: list[Smell] = []
    for line in result.stdout.strip().splitlines():
        parts = line.split(",")
        if len(parts) < 6:
            continue
        try:
            nloc = int(parts[0])
            ccn = int(parts[1])
            token_count = int(parts[2])  # noqa: F841
            param_count = int(parts[3])
            func_length = int(parts[4])
            func_name = parts[5].strip('"')
            # parts[6] is file, parts[7] is start line
            start_line = int(parts[7]) if len(parts) > 7 else 0
        except (ValueError, IndexError):
            continue

        if ccn > MAX_COMPLEXITY:
            smells.append(Smell(
                kind="complexity",
                detail=f"{{func_name}}() line {{start_line}}: complexity={{ccn}} (max {{MAX_COMPLEXITY}})",
                fix=FIXES["complexity"],
                line=start_line,
                function_name=func_name,
            ))

        if func_length > MAX_FUNCTION_LINES:
            smells.append(Smell(
                kind="long_function",
                detail=f"{{func_name}}() line {{start_line}}: {{func_length}} lines (max {{MAX_FUNCTION_LINES}})",
                fix=FIXES["long_function"],
                line=start_line,
                function_name=func_name,
            ))

        if param_count > MAX_PARAMETERS:
            smells.append(Smell(
                kind="too_many_params",
                detail=f"{{func_name}}() line {{start_line}}: {{param_count}} params (max {{MAX_PARAMETERS}})",
                fix=FIXES["too_many_params"],
                line=start_line,
                function_name=func_name,
            ))

    return smells


# ── Public API ────────────────────────────────────────────────────────


def check_file(file_path: str) -> list[dict]:
    """Run all applicable checks on a file. Returns list of smell dicts."""
    if _should_skip(file_path):
        return []

    try:
        with open(file_path, "r", encoding="utf-8", errors="replace") as f:
            source = f.read()
    except (OSError, PermissionError):
        return []

    ext = Path(file_path).suffix.lower()
    smells: list[Smell] = []

    # File-level checks (all languages)
    smells.extend(_check_file_length(source, file_path))
    smells.extend(_check_duplicates(source, file_path))

    # Language-specific checks
    if ext in PYTHON_EXTENSIONS:
        from smell_python import analyze_python
        smells.extend(analyze_python(source, file_path))
    elif ext in LIZARD_EXTENSIONS:
        smells.extend(_check_with_lizard(file_path))

    # Convert to dicts for JSON serialization
    return [
        {{
            "kind": s.kind,
            "detail": s.detail,
            "fix": s.fix,
            **({{ "line": s.line }} if s.line else {{}}),
            **({{ "function_name": s.function_name }} if s.function_name else {{}}),
        }}
        for s in smells
    ]
