"""Python AST analyzer for code smells.

Uses the stdlib `ast` module — no external dependencies required.
Calculates cyclomatic complexity, function length, nesting depth,
and parameter count for every function/method in a Python file.

Generated by /quality-init on {generated_date}.
"""

from __future__ import annotations

import ast
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from smell_types import Smell

from smell_types import (
    FIXES,
    MAX_COMPLEXITY,
    MAX_FUNCTION_LINES,
    MAX_NESTING_DEPTH,
    MAX_PARAMETERS,
    Smell,
)


# ── Cyclomatic complexity ─────────────────────────────────────────────


def _count_complexity(node: ast.AST) -> int:
    """Count decision points in an AST node (McCabe + boolean operators)."""
    count = 0
    for child in ast.walk(node):
        if isinstance(child, (ast.If, ast.For, ast.While, ast.ExceptHandler)):
            count += 1
        elif isinstance(child, ast.Assert):
            count += 1
        elif isinstance(child, ast.Try):
            # try itself is not a branch; handlers are counted above
            pass
        elif isinstance(child, ast.BoolOp):
            # Each `and`/`or` adds one branch per operator
            count += len(child.values) - 1
        elif isinstance(child, ast.comprehension):
            count += 1
            count += len(child.ifs)
    return count + 1  # base complexity


# ── Nesting depth ─────────────────────────────────────────────────────


_NESTING_TYPES = (
    ast.If,
    ast.For,
    ast.While,
    ast.With,
    ast.Try,
    ast.ExceptHandler,
)


def _max_nesting(node: ast.AST, depth: int = 0) -> int:
    """Compute the maximum nesting depth of control structures."""
    max_depth = depth
    for child in ast.iter_child_nodes(node):
        if isinstance(child, _NESTING_TYPES):
            max_depth = max(max_depth, _max_nesting(child, depth + 1))
        else:
            max_depth = max(max_depth, _max_nesting(child, depth))
    return max_depth


# ── Parameter count ───────────────────────────────────────────────────


def _count_params(func: ast.FunctionDef | ast.AsyncFunctionDef) -> int:
    """Count function parameters, excluding self/cls."""
    args = func.args
    all_args = args.posonlyargs + args.args + args.kwonlyargs
    count = len(all_args)

    # Exclude self/cls (first arg of methods)
    if all_args and all_args[0].arg in ("self", "cls"):
        count -= 1

    if args.vararg:
        count += 1
    if args.kwarg:
        count += 1

    return count


# ── Public API ────────────────────────────────────────────────────────


def analyze_python(source: str, file_path: str = "<unknown>") -> list[Smell]:
    """Analyze Python source code and return a list of smell findings."""
    try:
        tree = ast.parse(source, filename=file_path)
    except SyntaxError:
        return []  # Unparseable → skip, don't block

    smells: list[Smell] = []

    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue

        name = node.name
        line = node.lineno

        # Cyclomatic complexity
        complexity = _count_complexity(node)
        if complexity > MAX_COMPLEXITY:
            smells.append(Smell(
                kind="complexity",
                detail=f"{{name}}() line {{line}}: complexity={{complexity}} (max {{MAX_COMPLEXITY}})",
                fix=FIXES["complexity"],
                line=line,
                function_name=name,
            ))

        # Function length
        if hasattr(node, "end_lineno") and node.end_lineno is not None:
            length = node.end_lineno - node.lineno + 1
            if length > MAX_FUNCTION_LINES:
                smells.append(Smell(
                    kind="long_function",
                    detail=f"{{name}}() line {{line}}: {{length}} lines (max {{MAX_FUNCTION_LINES}})",
                    fix=FIXES["long_function"],
                    line=line,
                    function_name=name,
                ))

        # Nesting depth
        nesting = _max_nesting(node)
        if nesting > MAX_NESTING_DEPTH:
            smells.append(Smell(
                kind="deep_nesting",
                detail=f"{{name}}() line {{line}}: nesting depth {{nesting}} (max {{MAX_NESTING_DEPTH}})",
                fix=FIXES["deep_nesting"],
                line=line,
                function_name=name,
            ))

        # Parameter count
        params = _count_params(node)
        if params > MAX_PARAMETERS:
            smells.append(Smell(
                kind="too_many_params",
                detail=f"{{name}}() line {{line}}: {{params}} params (max {{MAX_PARAMETERS}})",
                fix=FIXES["too_many_params"],
                line=line,
                function_name=name,
            ))

    return smells
